# Render deployment Blueprint
version: "1"
services:
  # FlareSolverr service
  - name: flareresolverr
    type: web
    plan: free
    region: ohio
    runtime: image
    image:
      url: ghcr.io/flaresolverr/flaresolverr:latest
  # TachiDesk service
  - name: tachidesk
    type: web
    plan: free
    region: ohio
    runtime: image
    image:
      url: ghcr.io/cybardev/tachidesk:preview
    envVars:
      - key: BIND_PORT
        value: 443
      - key: BASIC_AUTH_ENABLED
        value: true
      - key: BASIC_AUTH_USERNAME
        sync: false
      - key: BASIC_AUTH_PASSWORD
        sync: false
      - key: EXTENSION_REPOS
        value: "https://github.com/keiyoushi/extensions"
      - key: FLARESOLVERR_ENABLED
        value: true
      - key: FLARESOLVERR_PROTOCOL
        value: https
      - key: FLARESOLVERR_URL
        fromService:
          name: flareresolverr
          type: web
          property: hostport
    domains:
      - manga.cybar.dev
