name: Build a container

on:
  workflow_call:
    inputs:
      tachidesk_release_type:
        required: true
        default: 'preview'
        description: 'Suwayomi Release Type'
        type: string
      do_upload:
        required: true
        default: true
        description: 'Should the image be uploaded to the registry?'
        type: boolean

env:
  server_repo: ${{ inputs.tachidesk_release_type == 'stable' && 'Suwayomi-Server' || 'Suwayomi-Server-preview' }}
  test_image_tag: "ghcr.io/${{ github.repository }}:testing"
  this_actions_run_url: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"

jobs:
  build_the_container:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # We want a full clone of the repo so that the rev-list count below is correct
          fetch-depth: 0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get latest release metadata
        id: get_latest_release_metadata
        run: |
          curl -s https://api.github.com/repos/suwayomi/${{ env.server_repo }}/releases/latest > ${{ runner.temp }}/latest_release.json
          release_url=$(jq -r '.assets[] | select(.content_type == "application/java-archive") | .browser_download_url' ${{ runner.temp }}/latest_release.json)
          release_tag=$(jq -r '.tag_name' ${{ runner.temp }}/latest_release.json)
          release_filename=$(basename $release_url)
          tachidesk_docker_git_commit=$(git rev-list --count HEAD)
          build_date=$(date "+%F")
          echo "release_url=$release_url" >> $GITHUB_OUTPUT
          echo "release_tag=$release_tag" >> $GITHUB_OUTPUT
          echo "release_filename=$release_filename" >> $GITHUB_OUTPUT
          echo "tachidesk_docker_git_commit=$tachidesk_docker_git_commit" >> $GITHUB_OUTPUT
          echo "build_date=$build_date" >> $GITHUB_OUTPUT

      # Now we build for all the platforms we support here.
      - name: Push container image to registry
        if: inputs.do_upload
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64/v8,linux/ppc64le,linux/s390x,linux/riscv64
          push: true
          build-args: |
            BUILD_DATE=${{ steps.get_latest_release_metadata.outputs.build_date }}
            TACHIDESK_RELEASE_TAG=${{ steps.get_latest_release_metadata.outputs.release_tag }}
            TACHIDESK_RELEASE_DOWNLOAD_URL=${{ steps.get_latest_release_metadata.outputs.release_url }}
            TACHIDESK_FILENAME=${{ steps.get_latest_release_metadata.outputs.release_filename }}
            TACHIDESK_DOCKER_GIT_COMMIT=${{ steps.get_latest_release_metadata.outputs.tachidesk_docker_git_commit }}
          tags: |
            ${{ inputs.tachidesk_release_type == 'stable' && 'ghcr.io/${{ github.repository }}:latest' || '' }}
            ghcr.io/${{ github.repository }}:${{ inputs.tachidesk_release_type }}
            ghcr.io/${{ github.repository }}:${{ steps.get_latest_release_metadata.outputs.release_tag }}
