name: Build container of the preview release

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'
      - '**/render.yaml'
  pull_request:

jobs:
  go:
    uses: ./.github/workflows/container.yml
    with:
      tachidesk_release_type: 'preview'
      # i.e. only upload the container on push-to-main
      do_upload: ${{ github.event_name == 'push' }}
    secrets: inherit
